server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/registrations/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
