server:
  port: 8084

spring:
  application:
    name: registration-service

  datasource:
    url: jdbc:mysql://localhost:3306/registrationdb
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      eventService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
